# Generated by Django 4.2.8 on 2023-12-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
