# Generated by Django 4.2.8 on 2023-12-27 07:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0005_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'Dashboard'), ('3', 'Statistics')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
