# Generated by Django 4.2.8 on 2023-12-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0006_portfolio_category_alter_portfolio_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
    ]
