# Generated by Django 4.2.8 on 2023-12-27 07:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0007_remove_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('python', 'Python'), ('dashboard', 'Dashboard'), ('statistic', 'Statistics')], max_length=100),
        ),
    ]
