# Generated by Django 4.2.8 on 2023-12-27 09:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0008_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_photos/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('filter-python', 'Python'), ('filter-dashboard', 'Dashboard'), ('filter-statistic', 'Statistics')], max_length=100),
        ),
    ]
