# Generated by Django 4.2.8 on 2023-12-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0009_portfolio_photo_alter_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='insight',
            field=models.CharField(blank=True, max_length=259),
        ),
    ]
