# Generated by Django 4.2.8 on 2023-12-27 11:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0010_portfolio_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('filter-python ', 'Python'), ('filter-dashboard ', 'Dashboard'), ('filter-statistic ', 'Statistics')], max_length=100),
        ),
    ]
