# Generated by Django 4.2.8 on 2023-12-27 13:29

import ckeditor_uploader.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0011_alter_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('filter-python', 'Python'), ('filter-dashboard', 'Dashboard'), ('filter-statistic', 'Statistics')], max_length=100),
        ),
    ]
