# Generated by Django 4.2.8 on 2023-12-30 10:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0012_alter_portfolio_body_alter_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('filter-python', 'Python'), ('filter-dashboard', 'Dashboard'), ('filter-statistic', 'Statistics'), ('filter-machine_learning', 'Machine Learning'), ('filter-scrapping', 'Scrapping'), ('filter-excel', 'Excel'), ('filter-supply_chain', 'Supply Chain')], max_length=100),
        ),
    ]
