# Generated by Django 4.2.8 on 2024-01-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesite', '0016_blogposts_subscribed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogposts',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
